### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#168]
Hello Jerome,

I tryed to install pyFAI on a windows machine with

pip install pyFAI.

I got this error message

error: can't copy 'dll\pthreadGC2.dll': doesn't exist or not a regular file

Cheers

**Comment by kif** [comment]
On Thu, 05 Feb 2015 02:19:20 -0800
picca <notifications@github.com> wrote:

> Hello Jerome,
> 
> I tryed to install pyFAI on a windows machine with

Can you specify the type (especially 32/64 bits)

Which path did it take: wheel or sources ? 

> pip install pyFAI.
> 
> I got this error message
> 
> error: can't copy 'dll\pthreadGC2.dll': doesn't exist or not a regular file

pthreadGC2.dll is for mingw32 and OpenMP.

Since:
http://aka.ms/vcpython27
it should make python much easier to compile on windows computers.

I need to update all this.

Thanks for the feed-back.

-- 
Jerome Kieffer <Jerome.Kieffer@terre-adelie.org>

**Comment by picca** [comment]
- windows 7 the computer is a 64 bits
- it seems to me that it used the source, because it compiled all the extensions.

**Comment by kif** [comment]
On Thu, 05 Feb 2015 03:38:16 -0800
picca <notifications@github.com> wrote:

> - windows 7 the computer is a 64 bits
> - it seems to me that it used the source, because it compiled all the extensions.

Great to know that.
I hope that with weel it will use them instead of re-compiling.

This is hence a bug in the setup.py.

-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by kif** [comment]
The computer may be 64 bits but the python is probably 32 bits because of this test:
if sys.platform == "win32":
    # This is for mingw32/gomp
    if tuple.__itemsize__ == 4:
        data_files[0][1].append(os.path.join("dll", "pthreadGC2.dll"))

**Comment by kif** [comment]
Until next release (which will be available as wheel):

python setup.py bdist_wheel
pip install dist\pyFAI*.whl
